const canvas = document.getElementById('worldMap'), ctx = canvas.getContext('2d');
const MAP_SIZE = 20; let TILE_SIZE = 40;
let playerPos = { x: 10, y: 10 };
let isMoving = false, moveProgress = 0, moveFrom = null, moveTo = null, moveStartTime = 0, moveDuration = 0, moveInterval = null;
let mapTiles = [], otherPlayers = [];
const TILES_DATA = { GRASS:{color:'#3a7e3a',icon:'🌿',name:'Трава',walkable:true,type:'empty'}, FOREST:{color:'#2a6a2a',icon:'🌲',name:'Лес',walkable:true,type:'combat',resource:'wood',enemy:'goblin'}, MOUNTAIN:{color:'#7a7a6a',icon:'🗻',name:'Горы',walkable:true,type:'combat',resource:'ore',enemy:'troll'}, VILLAGE:{color:'#8b6e4a',icon:'🏠',name:'Деревня',walkable:true,type:'safe'}, WATER:{color:'#2a6a8a',icon:'💧',name:'Вода',walkable:false,type:'empty'}, CAVE:{color:'#5a5a5a',icon:'⛰️',name:'Пещера',walkable:true,type:'combat',resource:'ore',enemy:'troll'}, BANDIT:{color:'#7a4a4a',icon:'⚔️',name:'Лагерь',walkable:true,type:'combat',enemy:'bandit'}, WASTELAND:{color:'#9a8a6a',icon:'🏜️',name:'Пустошь',walkable:true,type:'empty'} };
const MAP_LAYOUT = ["WGGGFGGGGGGGFGGGGFGP","WGGGGGGGGFGGGVGFGGGP","WGGFGGGGGGWGGGGGFGGP","WGGGGGGFGGGGFGGGGGGP","WGGGFGGGGGGGBFGGGFGP","WGMGGGGGFGGGGGGGFGGP","WGGGGGGGGGGGFGGGCGGP","WGGGGGFGGGGGGGGWGGGP","WGVGGGGGGGFGGGGGGGFP","WGGGFGGGGGGGGGGGGGGP","WGGGGGGGGGGFGGGGGGGP","WGGGFGGGGGMGGGGMGGGP","WGGGGGGVGGGGGBFGGGGP","WFGGGGGGGGGGGGGGGWGP","WGGGGGGBFCGGGGGGGGGP","WGGMGGGGGGFGGGGGGGGP","WGGGFGGGGGGGGGGGGVGP","WGGGGGGGGFGGGGGGGGGP","WGGGGGGGGGGGGGFGGGGP","WGGGFCGGGGGMGGGGGGMP"];
const letterToTile = { 'G':'GRASS','F':'FOREST','M':'MOUNTAIN','V':'VILLAGE','W':'WATER','C':'CAVE','B':'BANDIT','P':'WASTELAND' };
function generateMap() { for (let y=0; y<MAP_SIZE; y++) { mapTiles[y] = []; for (let x=0; x<MAP_SIZE; x++) { let t = letterToTile[MAP_LAYOUT[y]?.[x] || 'G'] || 'GRASS'; mapTiles[y][x] = { ...TILES_DATA[t], x, y }; } } }
function updateTileDisplaySize() { TILE_SIZE = canvas.width > 0 ? Math.floor(canvas.width / MAP_SIZE) : 40; }
function drawMap() { if (!canvas || !ctx) return; updateTileDisplaySize(); canvas.width = MAP_SIZE * TILE_SIZE; canvas.height = MAP_SIZE * TILE_SIZE; for (let y=0; y<MAP_SIZE; y++) { for (let x=0; x<MAP_SIZE; x++) { let t = mapTiles[y]?.[x]; if (!t) continue; ctx.fillStyle = t.color; ctx.fillRect(x*TILE_SIZE, y*TILE_SIZE, TILE_SIZE, TILE_SIZE); ctx.font = `${TILE_SIZE*0.5}px "Segoe UI Emoji"`; ctx.fillStyle = "#fff"; ctx.fillText(t.icon, x*TILE_SIZE + TILE_SIZE*0.2, y*TILE_SIZE + TILE_SIZE*0.7); ctx.strokeStyle = "#2a2a2a"; ctx.strokeRect(x*TILE_SIZE, y*TILE_SIZE, TILE_SIZE, TILE_SIZE); } } drawOtherPlayers(); let dx = playerPos.x*TILE_SIZE, dy = playerPos.y*TILE_SIZE; if (isMoving && moveFrom && moveTo) { let t = Math.min(1, (Date.now()-moveStartTime)/moveDuration); dx = (moveFrom.x*TILE_SIZE)*(1-t) + (moveTo.x*TILE_SIZE)*t; dy = (moveFrom.y*TILE_SIZE)*(1-t) + (moveTo.y*TILE_SIZE)*t; } ctx.font = `${TILE_SIZE*0.6}px "Segoe UI Emoji"`; ctx.fillStyle = "#ffdd88"; ctx.fillText("⚔️", dx + TILE_SIZE*0.2, dy + TILE_SIZE*0.75); }
function getCurrentTile() { return mapTiles[playerPos.y]?.[playerPos.x]; }
function startMoveTo(tx, ty) { if (isMoving) { addTechnicalLog("❌ Уже в пути"); return; } if (autoActive) { addTechnicalLog("❌ Нельзя во время боя/сбора"); return; } if (window.campActive) { addTechnicalLog("❌ Сначала снимите лагерь"); return; } if (!isLoggedIn) { addTechnicalLog("❌ Войдите в аккаунт"); return; } let tile = mapTiles[ty]?.[tx]; if (!tile?.walkable) { addTechnicalLog(`❌ Нельзя пройти`); return; } if (tx===playerPos.x && ty===playerPos.y) return; let dist = Math.abs(tx-playerPos.x) + Math.abs(ty-playerPos.y); moveDuration = dist * 2000; moveFrom = { x:playerPos.x, y:playerPos.y }; moveTo = { x:tx, y:ty }; isMoving = true; moveProgress = 0; moveStartTime = Date.now(); addTechnicalLog(`🚶 Идёте в ${tile.name} (${dist} клеток)`); if (moveInterval) clearInterval(moveInterval); moveInterval = setInterval(() => { if (!isMoving) { if (moveInterval) clearInterval(moveInterval); return; } moveProgress = Math.min(1, (Date.now()-moveStartTime)/moveDuration); drawMap(); if (moveProgress >= 1) { clearInterval(moveInterval); moveInterval = null; isMoving = false; playerPos = { x:moveTo.x, y:moveTo.y }; moveFrom = moveTo = null; drawMap(); updateActionButtons(); addTechnicalLog(`✅ Прибыли в ${getCurrentTile().name}`); if (Math.random() < 0.15 && typeof triggerRandomEvent === 'function') triggerRandomEvent(); savePlayerPosition(); } }, 50); }
function stopMoving() { if (moveInterval) { clearInterval(moveInterval); moveInterval = null; } isMoving = false; drawMap(); addTechnicalLog("⏹️ Движение остановлено"); updateActionButtons(); }
function drawOtherPlayers() { if (!ctx || !otherPlayers.length) return; for (let p of otherPlayers) { if (p.player_x===undefined || p.player_y===undefined) continue; let x = p.player_x * TILE_SIZE, y = p.player_y * TILE_SIZE; ctx.save(); ctx.strokeStyle = "#66ff66"; ctx.lineWidth = 2; ctx.strokeRect(x, y, TILE_SIZE, TILE_SIZE); ctx.font = `${TILE_SIZE*0.25}px monospace`; ctx.fillStyle = "#aaffaa"; ctx.fillText((p.username||"?").substring(0,6), x+3, y+TILE_SIZE-5); ctx.restore(); } }
async function loadOtherPlayers() { if (!supabaseClient || !isLoggedIn) return; let { data } = await supabaseClient.from("players").select("username, player_x, player_y").neq("username", currentPlayer.username).limit(20); otherPlayers = data || []; drawMap(); }
async function savePlayerPosition() { if (!supabaseClient || !isLoggedIn || !currentPlayer.id) return; await supabaseClient.from("players").update({ player_x: playerPos.x, player_y: playerPos.y }).eq("id", currentPlayer.id); }
canvas.addEventListener('click', (e) => { let rect = canvas.getBoundingClientRect(), scale = canvas.width / rect.width; let x = Math.floor((e.clientX - rect.left) * scale / TILE_SIZE), y = Math.floor((e.clientY - rect.top) * scale / TILE_SIZE); if (x>=0 && x<MAP_SIZE && y>=0 && y<MAP_SIZE) startMoveTo(x,y); });